# The lein image needed for most things.
docker_image: &docker_image
  image: circleci/node:16.13.1
jobs:
  check_syntax:
    docker:
      - *docker_image
    steps:
      - run: echo "this is the check_syntax job"
  echo:
    docker:
      - *docker_image
    steps:
      - run: echo ${TEST_BRICE_ENV_VAR}


workflows:
  version: 2

  main:
    jobs:
      - check_syntax
      - echo:
          context: test-restricted-context
          requires:
            - check_syntax
